<a href="https://colab.research.google.com/github/ju-ki/pytorch_basic/blob/master/basic_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensorsとは
* 配列や行列にとてもよく似ている。

#### Tensorの作成方法
* データから直接作る
* Numpy配列から作成する

In [1]:
import torch
import numpy as np

In [2]:
#直接
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
#Numpyから
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [3]:
display(x_data)
display(x_np)

tensor([[1, 2],
        [3, 4]])

tensor([[1, 2],
        [3, 4]])

In [4]:
#Numpyと同様に単位行列など作成可能
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor:\n {x_ones} \n')
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random Tensor:\n {x_rand} \n')

Ones Tensor:
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor:
 tensor([[0.8242, 0.9565],
        [0.8286, 0.0378]]) 



In [5]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.8164, 0.2465, 0.0602],
        [0.2159, 0.3710, 0.9002]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [6]:
#何に依存しているかも分かる
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [7]:
#100を超えるtensorの場合
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [8]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
#catで結合
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
#要素ごとの積
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor \n {tensor * tensor} \n")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [11]:
#２つのテンソル間の行列の乗算を計算
print(f'tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n')
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [12]:
#Tensorの加減
print(tensor, "\n")
tensor.add_(5)
print(tensor)
tensor.subtract_(3)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
tensor([[3., 2., 3., 3.],
        [3., 2., 3., 3.],
        [3., 2., 3., 3.],
        [3., 2., 3., 3.]])


In [13]:
#Tensorからnumpyへの変換
t = torch.ones(5)
print(f't:{t}')
n = t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


In [14]:
#NumpyはTensorの変更を反映している
t.add_(1)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

In [16]:
#Tensorも同様にNumpyでの変更も反映している
np.add(n, 1, out=n)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n:[2. 2. 2. 2. 2.]
